// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PSYCO.Ranpod.DataCollector.Data;

namespace PSYCO.Ranpod.DataCollector.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200118111609_newLogModel")]
    partial class newLogModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PSYCO.Ranpod.DataCollector.DomainObjects.LogModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Data");

                    b.Property<string>("GetPMDLProStatusString0");

                    b.Property<string>("GetPMDLProStatusString1");

                    b.Property<string>("GetPMDLProStatusString2");

                    b.Property<bool>("IsPMDLProRunning");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<string>("MyProperty");

                    b.Property<int>("RegistryAppID");

                    b.Property<int>("RegistryDefaultProtectionMode");

                    b.Property<DateTime>("RegistryExpireDate");

                    b.Property<string>("RegistryLicenseData");

                    b.Property<int>("RegistryOrgID");

                    b.Property<string>("RegistryPassword");

                    b.Property<string>("RegistryRestrictedPath");

                    b.Property<int>("RegistryServerID");

                    b.Property<string>("RegistryTrustedPath");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
